### ISSUE TITLE
Docker-compose config

### ISSUE THREAD

**Issue by Morgan-6Freedom** [nvllsvm/jellysub#4]
Hello.
I have writtend down 

```
version: 3.8
services:
  jellyfin:
    image: nvllsvm/jellysub
    container_name: jellysub
    JELLYSUB_UPSTREAM_URL: https://my.jellyfin.server
    JELLYSUB_HTTP_PORT: 1234:1234
    restart: "unless-stopped"
```

in my docker compose but it's not working. I got this error :
> Unsupported config option for services.jellyfin: 'JELLYSUB_HTTP_PORT'

How should I name the parameters ?

**Comment by nvllsvm** [comment]
Environment variables are specified like so in in Docker Compose:
```
version: 3.8
services:
  jellyfin:
    image: nvllsvm/jellysub
    container_name: jellysub
    environment:
      JELLYSUB_UPSTREAM_URL: https://my.jellyfin.server
      JELLYSUB_HTTP_PORT: 1234:1234
    restart: "unless-stopped"
```
